package com.demospace.parent_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TestDO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public TestDO() {
    }




}